name: datamanagement
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - scipy
  - cython
  - pandas
  - seaborn
  - ruamel_yaml
  - pytest
  - nose
  - jupyter
  - ipython
  - click
  - h5py
  - tqdm
  - openpyxl
  - vispy
  - traitlets
  - joblib
  - requests
  - git
  - sip
  - pycodestyle
  - pip:
    - pynwb
    - quantities
    - tkfilebrowser
    - xmljson
    - expipe
    - exdir
    - qtconsole
    - PyQt5==5.9
    - colorcet
    - spikeinterface
    - git+https://github.com/cortex-lab/phy@dev
    - git+https://github.com/cortex-lab/phylib
